// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVhPMUPFiCCJes2CbFQ-hcGZI6FW6GuCI',
    appId: '1:1014080356550:web:dcba1e4ffa3b9aead557c7',
    messagingSenderId: '1014080356550',
    projectId: 'eyes-on-plant',
    authDomain: 'eyes-on-plant.firebaseapp.com',
    storageBucket: 'eyes-on-plant.firebasestorage.app',
    measurementId: 'G-DERV4NQTQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfJUksWSdfzR-96zw9DGvHiluyWa4lKb4',
    appId: '1:1014080356550:android:895fec573c3b3644d557c7',
    messagingSenderId: '1014080356550',
    projectId: 'eyes-on-plant',
    storageBucket: 'eyes-on-plant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiucZ9SyTOhwIqLc-MHL0mV042eKluys',
    appId: '1:1014080356550:ios:03a10931bc7afe7cd557c7',
    messagingSenderId: '1014080356550',
    projectId: 'eyes-on-plant',
    storageBucket: 'eyes-on-plant.firebasestorage.app',
    iosBundleId: 'com.example.eyesOnPlant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiucZ9SyTOhwIqLc-MHL0mV042eKluys',
    appId: '1:1014080356550:ios:03a10931bc7afe7cd557c7',
    messagingSenderId: '1014080356550',
    projectId: 'eyes-on-plant',
    storageBucket: 'eyes-on-plant.firebasestorage.app',
    iosBundleId: 'com.example.eyesOnPlant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVhPMUPFiCCJes2CbFQ-hcGZI6FW6GuCI',
    appId: '1:1014080356550:web:d9535b4e0a53c85fd557c7',
    messagingSenderId: '1014080356550',
    projectId: 'eyes-on-plant',
    authDomain: 'eyes-on-plant.firebaseapp.com',
    storageBucket: 'eyes-on-plant.firebasestorage.app',
    measurementId: 'G-RK6Z2LHESW',
  );
}
